### ISSUE TITLE
Kan inte längre hämta XML-fil

### ISSUE THREAD

**Issue by GudrunSchyman** [pettersoft/apk#1]
I och med att systembolaget uppdaterat sin hemsida funkar inte längre länken som hämtar XML-filen.

Fungerar om länken ändras till https://old.systembolaget.se/api/assortment/products/xml i MainForm.cs

**Comment by pettersoft** [comment]
Fixat, tack för notifieringen Gudrun, vi får se hur länge dom sparar det gamla API:et.

**Comment by GudrunSchyman** [comment]
Gamla apit funkar inte längre sedan uppdateringen av Systembolagets sida.

**Comment by pettersoft** [comment]
Jaha, det var tråkigt. Tack för notifikationen. Jag får skrota det här
projektet. Fanns mest för kuls skull ändå.

fre 19 feb. 2021 kl. 19:25 skrev GudrunSchyman <notifications@github.com>:
